### ISSUE TITLE
icon doesnt render in  <content select="[item-icon]">

### ISSUE THREAD

**Issue by mattiLeBlanc** [PolymerElements/paper-item#12]
Hi,

While using Meteor with Iron-router or Flow-router, I am experiencing rendering issues with the paper-icon-item.

When I simply try to render the following in my global layout
```
        paper-icon-item
            iron-icon(icon="social:group" item-icon) inbox
```
it doesnt show anything, except for when I catch the WebComponentsReady event and only render the paper-icon-item in Meteor when this event has fired.

However, then the icon is not rendered within the content select="[item-icon]' area, but outside:

```
<paper-icon-item role="listitem" class="x-scope paper-icon-item-0">
    <div id="contentIcon" class="content-icon layout horizontal center style-scope paper-icon-item">
      
    </div>
    
  <iron-icon icon="social:group" item-icon="" class="x-scope iron-icon-0"><svg viewBox="0 0 24 24" preserveAspectRatio="xMidYMid meet" class="style-scope iron-icon" style="pointer-events: none; display: block; width: 100%; height: 100%;"><g class="style-scope iron-icon"><path d="M16 11c1.66 0 2.99-1.34 2.99-3S17.66 5 16 5c-1.66 0-3 1.34-3 3s1.34 3 3 3zm-8 0c1.66 0 2.99-1.34 2.99-3S9.66 5 8 5C6.34 5 5 6.34 5 8s1.34 3 3 3zm0 2c-2.33 0-7 1.17-7 3.5V19h14v-2.5c0-2.33-4.67-3.5-7-3.5zm8 0c-.29 0-.62.02-.97.05 1.16.84 1.97 1.97 1.97 3.45V19h6v-2.5c0-2.33-4.67-3.5-7-3.5z" class="style-scope iron-icon"></path></g></svg>
    <iron-meta id="meta" type="iconset" class="style-scope iron-icon"></iron-meta>
  inbox</iron-icon></paper-icon-item>
```

When I manually edit the source in Chromes Dev Tools and add another paper-icon-item below the broken one, will it render correctly.

I realise this issue is related to Meteor, however all the scripts should be loaded in correct order and I only render the template part after WebComponentsReady fired.
I can work around with a separate iron-icon in a paper-item, that works fine.

**Comment by Joostvanderlaan** [comment]
+1

**Comment by notwaldorf** [comment]
Tentatively assigning this to @justinfagnani since he's doing a whole bunch of framework interop things. Also /cc @robdodson for ideas.

**Comment by robdodson** [comment]
I'm curious, if you include webcomponents.js and set Polymer to [use Shadow DOM](https://www.polymer-project.org/1.0/docs/devguide/settings.html), does it work?

**Comment by mattiLeBlanc** [comment]
@robdodson I believe it works only on first render. However, I would have to test it out, but honestly postponed my 0.5 to 1.0 migration because I need to deliver soon.

There is a thread on the Meteor forum: https://forums.meteor.com/t/polymer-1-0-and-iron-router-or-flow-router/5148/16

Latest news it does work with safari and chrome but not for FF.

**Comment by notwaldorf** [comment]
Is this still an issue? There have been a bunch of fixes around icons and how they get loaded.

**Comment by notwaldorf** [comment]
Closing as there hasn't been any activity on this recently
