### ISSUE TITLE
No demo in catalog

### ISSUE THREAD

**Issue by ebidel** [PolymerElements/paper-item#13]

**Comment by morethanreal** [comment]
I think this is a catalog bug. The `<paper-item>` docs are unreachable from the catalog also. Maybe related to https://github.com/Polymer/polymer-element-catalog/issues/113, https://github.com/Polymer/polymer-element-catalog/issues/96, https://github.com/Polymer/polymer-element-catalog/issues/77?

**Comment by notwaldorf** [comment]
Closing, since I see this in the catalog.
