### ISSUE TITLE
 Anchor element children click target area.

### ISSUE THREAD

**Issue by jackeown** [PolymerElements/paper-item#21]
This issue is really annoying me.  A menu with links is a fairly common use case and as such I hope this gets fixed soon.  I'm just posting a link to the issue on the old repo so you guys are aware that it's still not fixed.

https://github.com/Polymer/paper-item/issues/14

**Comment by craftgear** [comment]
I found a workaround on paper-menu issues.

https://github.com/PolymerElements/paper-menu/issues/22#issuecomment-113199527

On the Stackoverflow post a user named sensor shows how to use 'on-tap' to detect tappings/clickings.

So the following code would mitigate the pain a bit.

```
  <paper-menu>
    <paper-item on-tap="onSelect"><a href="/">TOP</a></paper-item>
  </paper-menu>
  
  <script>
    Polymer({
      onSelect: function(e){
        var link = e.currentTarget.querySelector('a');
        if(link) {
         link.click();
       }
      }
    });
  </script>
```

But honestly, this is ugly.
It destorys the beauty of "There is always an element."

And I can't understand why Polymer dev team doesn't include paper-item with a tags in any demos whatoever.

Maybe they tried it and know it doesn't work so avoid using them together? idk.

**Comment by Miliooo** [comment]
I ran into the same problem, this is really holding me back...

**Comment by craftgear** [comment]
@Miliooo I'd like to recommend you to look at Riot.JS + Material Design Lite.
IMHO, it's much more productive and pragmatic at this point of time.

Though I think I still keep watching how Polymer evolves.

**Comment by rubenstolk** [comment]
In general this issue is big, any element within `paper-item` cannot have their own `on-tap` listeners, simply overruled by the focus event of the paper-item or whatever.

**Comment by mcarey1590** [comment]
I have found this is due to the absolute position applied to the :before of paper-item that gives the focused/selected visual background. One way to solve this is to override the positioning using the mixin --paper-item-focused-before. A proper fix needs to be put into place though.

**Comment by ronnyroeller** [comment]
+1

**Comment by morficus** [comment]
+1

**Comment by bicknellr** [comment]
Why not just wrap the `paper-item` with the link? ([demo](http://jsbin.com/wuyecerori/edit?html,output))

**Comment by abdonrd** [comment]
Similar discussion here: https://github.com/PolymerElements/paper-button/issues/35#issuecomment-165987461.

**Comment by eximius313** [comment]
+1

**Comment by Nemo64** [comment]
Why is it, that all these paper item/button etc elements can't just receive a `href` as an attribute. It would make everything so much easier. Allows correct coloring inside the element etc.

**Comment by eximius313** [comment]
yup, would be great...

**Comment by MarcMouallem** [comment]
If it helps anyone I am doing something like this to at least get the styling to work.

    /* HACK: Makes <a> work with <paper-item> selected item styling.
     * https://github.com/PolymerElements/iron-elements/issues/37*/
    a.iron-selected paper-item,
    a.iron-selected paper-icon-item{
      font-weight: bold;
    }
    /* HACK: Makes <a> work with <paper-item> selected item styling.
     * https://github.com/PolymerElements/iron-elements/issues/37*/
    a:focus {
      outline: none;
    }
    /* HACK: Makes <a> work with <paper-item> focus styling.
     * https://github.com/PolymerElements/iron-elements/issues/37 */
    a:focus paper-item:before,
    a:focus paper-icon-item:before {
      @apply(--layout-fit);
      background: currentColor;
      content: '';
      opacity: var(--dark-divider-opacity);
    }

P.S. `<a>` must wrap `<paper-item>` and not the other way around so that the entire item, including any icons, is part of the "hit" area.
