### ISSUE TITLE
<paper-icon-item> used in demo does not exist (anymore)

### ISSUE THREAD

**Issue by stevenroose** [PolymerElements/paper-item#22]
Here it is: https://github.com/PolymerElements/paper-item/blob/master/demo/index.html#L91

What should it be replaced with?

**Comment by notwaldorf** [comment]
I still see it in master: https://github.com/PolymerElements/paper-item/blob/master/paper-icon-item.html. Not sure what you mean by "does not exist" :)

**Comment by stevenroose** [comment]
Ah ok. I thought all `<polymer-emenents>` were stored at `PolymerElements/polymer-emenents`. So there's no way to know that `<paper-icon-item>` does not follow this pattern.

**Comment by notwaldorf** [comment]
You can see from the import (https://github.com/PolymerElements/paper-item/blob/master/demo/index.html#L28). I agree that most elements are alone in their repositories, but that's not always true (`paper-submenu` and `paper-menu` are in the same repo, some behaviours, etc).
