### ISSUE TITLE
please fix encoding in this file paper-item-shared.css

### ISSUE THREAD

**Issue by triune** [PolymerElements/paper-item#26]
Chrome always complains in the console...
Resource interpreted as Document but transferred with MIME type text/css: "https://dev.g.x/assets/bower_components/paper-item/paper-item-shared.css".

**Comment by notwaldorf** [comment]
This should have been fixed in https://github.com/PolymerElements/paper-item/pull/25.

**Comment by triune** [comment]
Confirmed resolved.
