### ISSUE TITLE
Focus styles don't work with shadow dom enabled

### ISSUE THREAD

**Issue by zclark** [PolymerElements/paper-item#34]
Run the paper-menu demo with
```js
Polymer = { dom: "shadow" };
```
If you focus any of the paper-item's they go completely grey
![screen shot 2015-10-15 at 4 21 19 pm](https://cloud.githubusercontent.com/assets/4033334/10530109/ee00d312-7358-11e5-9cac-4f25fcc25132.png)

Seems to be being addressed by PR #33

**Comment by summers173** [comment]
@zclark is right

NO SHADOW DOM looks liike this

![imagen 002](https://cloud.githubusercontent.com/assets/5115255/10546989/167c8662-73f7-11e5-86ba-ea53e3f33253.jpg)

SHADOW DOM looks like this

![imagen 003](https://cloud.githubusercontent.com/assets/5115255/10546991/1ed794f0-73f7-11e5-81c0-7c0ab85fc703.jpg)

I found that this is the problem

:host(:focus:before) {
  content: '';
        background: currentColor;
}


:host(:focus:before) {
  position:absolute;
      top:0;
      right:0;
      bottom:0;
      left:0;

        opacity:0.12;;
}

specially the "background: currentColor;" part

Regards

**Comment by summers173** [comment]
I manage to temporary fix the issue with this

body /deep/ paper-item:focus {
		background: transparent !important;
		opacity: 1 !important;
	}	

Until the @polymer-ci fix it, regards

**Comment by zclark** [comment]
Fixed in 1.0.5 by PR #33

**Comment by notwaldorf** [comment]
Fixed!

**Comment by tpluscode** [comment]
Hi. I think there is some kind of regression here. As of 1.1.0 similar problem occurs with `:focus` background, but both in Shadow and Shady DOM. Works fine in 1.0.7. Here's a minimal repro: http://t-code.pl/paper-item-background/

**Comment by tpluscode** [comment]
Ok, sorry. I've just discovered that issue #55 is about that very problem I had
