### ISSUE TITLE
paper-item content not center-aligned in IE11

### ISSUE THREAD

**Issue by sbley** [PolymerElements/paper-item#35]
The default paper-item stylesheet contains `align-items: center` which aligns the content vertically centered. This does not work in IE 11:
![ie](https://cloud.githubusercontent.com/assets/686538/10535892/ef573204-73e6-11e5-8a5b-4ae984e1e913.png)
A solution is described in http://stackoverflow.com/questions/19371626/flexbox-not-centering-vertically-in-ie. In addition to `min-height` an attribute `height` should be added.
Could you please fix this in the paper-item stylesheet?

**Comment by jdepypere** [comment]
I'm still seeing some issues in IE11 with the two-line items:
**IE11**
![ie11](https://cloud.githubusercontent.com/assets/3522063/12427405/51888098-bedf-11e5-93cf-c031ded1b431.PNG)
**Chrome**
![chrome](https://cloud.githubusercontent.com/assets/3522063/12427407/53f083bc-bedf-11e5-96b6-c23a9b98625b.PNG)

The single-line items do seem to display correctly.

**Comment by jdepypere** [comment]
I'm still seeing some issues in IE11 with the two-line items:
**IE11**
![ie11](https://cloud.githubusercontent.com/assets/3522063/12427405/51888098-bedf-11e5-93cf-c031ded1b431.PNG)
**Chrome**
![chrome](https://cloud.githubusercontent.com/assets/3522063/12427407/53f083bc-bedf-11e5-96b6-c23a9b98625b.PNG)

The single-line items do seem to display correctly.

**Comment by MaheshKonne** [comment]
Is there any workaround for this issue?

**Comment by sujay1848** [comment]
This is still visible in the demo on IE 11.
