### ISSUE TITLE
Why paper-item has the Polymer.IronButtonState behavior if there is a "non-interactive list item"?

### ISSUE THREAD

**Issue by abdonrd** [PolymerElements/paper-item#38]
Why `paper-item` has the `Polymer.IronButtonState` behavior if there is a "non-interactive list item"?

**Comment by notwaldorf** [comment]
Sorry, that's my bad. I updated the docs, but we left the `README.md` behind and not updated.

**Comment by abdonrd** [comment]
What docs? Here say the same: https://elements.polymer-project.org/elements/paper-item.

**Comment by notwaldorf** [comment]
Argh, good call. It's a PR that hasn't landed yet: https://github.com/PolymerElements/paper-item/pull/29/files

**Comment by abdonrd** [comment]
:+1: :grin:

**Comment by abdonrd** [comment]
I think that we can close this PR.

The elements catalog isn't updated, but the repository was fixed in the #29. :smiley:
