### ISSUE TITLE
Add several actions on `paper-item`element causes some problems.

### ISSUE THREAD

**Issue by RoXuS** [PolymerElements/paper-item#42]
```html
<paper-item>
  <paper-item-body on-tap="_tap1">
    <div>
      <span>[[myVar]]</span>
    </div>
   </paper-item-body>
  <div id="divTap2" on-tap="_tap2">
    <paper-icon-button icon="refresh"></paper-icon-button>
  </div>
</paper-item>
```
## Expected outcome

`_tap1` function and `_tap2` function are launched when I click respectively on `paper-item-body` and on `div#divTap2`.

## Actual outcome

Only the `_tap2` function is fired.

## Steps to reproduce

1. Put a `paper-item-body` element in a `paper-item`.
2. Add on tap listener on `paper-item-body`.
3. Click the `paper-item-body`.
4. The `_tap1` function is never called.

## When the problem occurred

This problems appears since the 1.0.4 with [this commit](https://github.com/PolymerElements/paper-item/commit/b50fd1cc6750d18d0b519c64ef642923d29d1d3c#diff-d50c1401bd186d003717e3b9e92a752eR20).

## Quick fix

Set `position: relative;` to the `paper-item-body`.

## Question

We want to use several actions in a list of `paper-item` like it's described in [the md specs](https://www.google.com/design/spec/components/lists.html#lists-content).
![](https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0Bx4BSt6jniD7bTlwblZleHIwU1U/components_lists_content2.png)
**Maybe we use the bad** `paper-element` ?

**Comment by notwaldorf** [comment]
I think this was fixed in https://github.com/PolymerElements/paper-item/pull/62. Here's a jsbin showing everything works as expected: http://jsbin.com/vibenu/edit?html,output

**Comment by RoXuS** [comment]
Exactly ! Thx
