### ISSUE TITLE
Behaviour different between chrome and safari on tap

### ISSUE THREAD

**Issue by spirylics** [PolymerElements/paper-item#46]
https://elements.polymer-project.org/elements/iron-list?view=demo:demo/selection.html&active=iron-list.

On safari you have to tap twice to delete item (right panel), not on chrome.

**Comment by notwaldorf** [comment]
@blasten do you think is this an `iron-list` bug?

**Comment by blasten** [comment]
@notwaldorf  I can reproduce this issue.
