### ISSUE TITLE
disabled property makes children paper-button unclickable/selectable

### ISSUE THREAD

**Issue by AndreasGalster** [PolymerElements/paper-item#48]
Something like this breaks the paper-buttons behavior, including event listeners on the button.

https://gist.github.com/AndreasGalster/19177c15ffd0bf55e793

**Comment by AndreasGalster** [comment]
Just an update but you probably already know this since it's a behavior from iron-select I think: This disables interactions with any element that has a selectable state, so also paper-checkbox for example.

**Comment by notwaldorf** [comment]
Why doesn't that make sense? If you're disabling a `paper-item`, I would expect anything inside it to be disabled as well. Isn't that the whole point of disabling something?

**Comment by abdonrd** [comment]
I think that I have a case of use.

I have this card, with a list of items. I use paper-item for the design:

<img width="338" alt="screen shot 2015-12-15 at 16 50 41" src="https://cloud.githubusercontent.com/assets/1007051/11815456/21ef5482-a34c-11e5-8bbd-c93164983dee.png">

I need to add the `disabled` property because I don't want any interaction with the items.
But... I have a paper-icon-button. And I want that when the button is pressed, go to slides link.

**Comment by notwaldorf** [comment]
If you want interaction with _some_, not all of the items, shouldn't you make those particular items disabled, not the entire item as a whole?

I don't think there's any native element (or, really, any other element), where if you add `disabled` to a parent, it selectively enables children nodes.

**Comment by abdonrd** [comment]
@notwaldorf Yes, in my case maybe I shouldn't use the `paper-item`, because I don't want interaction with it.

**Comment by cdata** [comment]
> I need to add the disabled property because I don't want any interaction with the items.

In my opinion, this is not a good case for using `disabled`. If you want to selectively enable interaction with some elements, it is better to enforce that on a case-by-case basis for each element. So, if you have three buttons in a `paper-item`, but only one of the buttons should be interactive, the other two should be `disabled` manually. If the `paper-item` should not be focusable, the user can provide a `tabindex="-1"` for the `paper-item`.

Also, please consider this description of `aria-disabled` from the WAI-ARIA spec:

> Indicates that the element is perceivable but disabled, so it is not editable or otherwise operable ... The state of being disabled **applies to the current element and all focusable descendant elements** of the element on which the aria-disabled attribute is applied.

http://www.w3.org/TR/2011/CR-wai-aria-20110118/states_and_properties#aria-disabled

**Comment by abdonrd** [comment]
@cdata thanks for the answer! Good arguments, you are right.

I make a test with `tabindex="-1"` and doesn't work: http://jsbin.com/jiqexuriwu/edit?html,output

**Comment by notwaldorf** [comment]
Closing this, since `paper-item` is fine.

**Comment by abdonrd** [comment]
Okay closing the issue!

But, the `tabindex="-1"` doesn't work for me: http://jsbin.com/jiqexuriwu/edit?html,output
You mean something else, @cdata?
