### ISSUE TITLE
Focused ::before content hides item text and coloring is off

### ISSUE THREAD

**Issue by ebidel** [PolymerElements/paper-item#72]
https://github.com/PolymerElements/paper-item/blob/master/paper-item-shared-styles.html#L51 uses `background: currentColor` to create `::before` content on focus. 

Unfortunately, there's two problems with this.

1. it overwrites our `.iron-selected` color
2. The  `::before` content is rendering above the item's text. I think it needs a `z-index: -1;`:

<img width="624" alt="screen shot 2016-01-26 at 8 42 29 am" src="https://cloud.githubusercontent.com/assets/238208/12587344/c8bd0b10-c408-11e5-8660-0030da4178f3.png">

Should be:

<img width="576" alt="screen shot 2016-01-26 at 8 48 11 am" src="https://cloud.githubusercontent.com/assets/238208/12587512/8d476048-c409-11e5-89a8-995ae93cec50.png">

**Comment by ebidel** [comment]
@bicknellr are you adopting this element? :)

**Comment by ebidel** [comment]
It looks like this may be a timing issue with async vulcanized imports. The opacity in https://github.com/PolymerElements/paper-item/blob/master/paper-item-shared-styles.html#L53 is not being applied, but calling `Polymer.updateStyles()` after the app loads fixes it.

**Comment by ebidel** [comment]
It's worth noting we're using native shadow dom.  

Our current workaround is to force-add the opacity

```
--paper-item-focused-before: {
  opacity: 0.12;
};
```

**Comment by ebidel** [comment]
I looks like this is ultimately a timing issue with the style shimmer. We added `<link rel="import" href="../bower_components/paper-styles/color.html">` to the top of our elements.html bundle and this fixed the issue. Looks like the styles were not yet defined by the time paper-item was being registered in our vulcanized output.

Going to leave this open if you want to investigate, but feel free to close.

**Comment by bicknellr** [comment]
@ebidel Yeah, I'll be taking this one on.

**Comment by bicknellr** [comment]
Oh, from your last comment this sounds like it may be an issue with vulcanize.

**Comment by ebidel** [comment]
Not sure. paper-item-shared-styles.html imports paper-styles/color.html correctly. When everything gets vulcanized, it means the css properties defines will still come before paper-item registers itself (an applies the properties). 

It's a bit hard for me to test because it doesnt happen locally, only on our server (https://codelabs.developers.google.com/). However, we added the extra import as described in https://github.com/PolymerElements/paper-item/issues/72#issuecomment-175162931 so things are working now :)

Im going to close this since there's a lot going on in our app (async imports, body is="body-bind", lazy loaded imports, vulcanize). Hard to reduce to a small case.
