### ISSUE TITLE
Add a label property to allow custom label in paper-dropdown-menu

### ISSUE THREAD

**Issue by kungufli** [PolymerElements/paper-item#76]
I think it might be useful to have a `label` String property on `paper-item` so you could set a label to be displayed in a `paper-dropdown-menu` instead of the full trimmed text content.
For example, you could use it like this:

```
<paper-dropdown-menu>
    <paper-menu class="dropdown-content">
        <paper-item label="item 1">Item 1 - short description</paper-item>
        <paper-item label="item 2">Item 2 - short description</paper-item>
        <paper-item label="item 3">Item 3 - short description</paper-item>
    </paper-menu>
</paper-dropdown-menu>
```

and when you select the first item from the `paper-menu` you will have "item 1" displayed in the `paper-dropdown-menu` instead of "Item 1 - short description".
Note that `paper-dropdown-menu` already try to read the `label` property of the selected item, so it not require any change and will continue to show the trimmed text content of the `paper-item` if no `label` is specified.

**Comment by bicknellr** [comment]
As you mentioned, it looks like this is supposed to work, so I think this would be considered a bug in `paper-dropdown-menu`. @miztroh has a PR which should solve this issue: PolymerElements/paper-dropdown-menu#131.

**Comment by jptrainor** [comment]
+1 

Encountered this just now. The paper-dropdown-menu docs and demo lead on to believe that a label property on paper-item will be reflected back to the dropdown selectedItemLabel property.... but there is no label property on paper time.

**Comment by jptrainor** [comment]
This works as an alternative:

```
<paper-dropdown-menu>
    <paper-listbox class="dropdown-content" attr-for-selected="data-label" selected="{{selectedItemLabel}}">
        <paper-item data-label="item 1">Item 1 - short description</paper-item>
        <paper-item data-label="item 2">Item 2 - short description</paper-item>
        <paper-item data-llabel="item 3">Item 3 - short description</paper-item>
    </paper-menu>
</paper-dropdown-menu>


```

**Comment by kungufli** [comment]
@bicknellr Thanks
