### ISSUE TITLE
Update with full Material Design lists spec

### ISSUE THREAD

**Issue by abdonrd** [PolymerElements/paper-item#79]
#### Three-line list

When the second and the third line is the same element/paragraph.

<a href="https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0Bzhp5Z4wHba3dXNub0hnVG13blE/components_lists_keylines_three1.png"><img src="https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0Bzhp5Z4wHba3dXNub0hnVG13blE/components_lists_keylines_three1.png" width="360"></a>
#### The top right text

| <a href="https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0Bx4BSt6jniD7ckJuUHNnUVlVYTQ/components_lists_content1.png"><img src="https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0Bx4BSt6jniD7ckJuUHNnUVlVYTQ/components_lists_content1.png" width="300"></a> | <a href="https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B6Okdz75tqQsZmJRelNHTjVkSDQ/components_lists_keylines_three12.png"><img src="https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B6Okdz75tqQsZmJRelNHTjVkSDQ/components_lists_keylines_three12.png" width="360"></a> |
| --- | --- |

**Comment by notwaldorf** [comment]
Is this not possible with the existing elements, or are you just asking to add this to the demo?

**Comment by abdonrd** [comment]
I was thinking of updating the element to support it.

**Comment by abdonrd** [comment]
As far as I know, the Polymer Elements are not going to continue developing. So I close this issue.
