### ISSUE TITLE
[paper-item::_flattenBehaviorsList]: behavior is null, check for missing or 404 import 

### ISSUE THREAD

**Issue by 34code** [PolymerElements/paper-item#80]
### Description

Getting an error in console upon importing paper-item in polymer 1.4.0

`[paper-item::_flattenBehaviorsList]: behavior is null, check for missing or 404 import`

### Expected outcome

There should be no error logged in the console

### Actual outcome

Getting this console warning from polymer-micro.html:383

`[paper-item::_flattenBehaviorsList]: behavior is null, check for missing or 404 import`

### Live Demo

N/A

### Steps to reproduce

1. Put a `paper-item` element in the page.
2. Open the page in a web browser.

code used:

````<paper-dropdown-menu label="Country">
              <paper-listbox class="dropdown-content" selected="0">
                <paper-item>USA</paper-item>
              </paper-listbox>
            </paper-dropdown-menu>````
### Browsers Affected
<!-- Check all that apply -->
- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by bicknellr** [comment]
Hi @34code, [I don't seem to get any console messages about null behaviors](http://jsbin.com/suziqa/1/edit?html,output); any extra details you can provide? (Did you `check for missing or 404 import`? :) 404 sounds like a likely culprit - take a look at the Dev Tools 'Network' tab.)

**Comment by 34code** [comment]
gave up and decided to move entire project to `materialize` which is built using webcomponents I believe.. 

I tried checking for various potential missing imports but could not identify which one or what was not being imported.. The polymer project just has so many relative imports and it is hard to figure out which one is missing if any.

**Comment by bicknellr** [comment]
Yeah, getting set up can be a bit tricky sometimes given the number of small pieces to assemble. If you happen(ed) to find out anything else about what was going on, please post something here and I'll reopen.

**Comment by kvnapavl** [comment]
I know this is closed, but just to add some more context...  I got this error in the shop-app demo when importing `paper-progress` async outside the app shell from index.html.

**Comment by phidias51** [comment]
I'm getting this with **firebase-query** and **iron-textarea**.  The problem is that the code that's reporting the error cannot tell you which behavior is missing.  Running **polymer lint** on those components doesn't reveal any missing dependencies. I'm running Polymer 1.8.0. I tried installing previous versions, and it doesn't seem to make any difference.  The problem seems to have been reported for a while now, and there are problems trying to reproduce this.  Running **bower update** doesn't solve the problem either.

**Comment by phidias51** [comment]
I noticed that the dependencies in the paper-fab component seem to be a bit out of date. Both the polymer dependency and the paper-behaviors dependency.

**Comment by ackushiw** [comment]
I noticed this as well when using **firebase-document** in a lazy loaded page. I Imported it into the app-shell and it started working.
