### ISSUE TITLE
Focus shade appears under position:absolute children

### ISSUE THREAD

**Issue by tommie** [PolymerElements/paper-item#81]
### Description
For material design, I'm using `position:absolute; right: 0;` to place "secondary actions" within an item. The actions have a background to ensure they obscure the text behind. The `:focus` shade appears under the action elements.

One solution would be to use `:after` for the shade instead of `:before` (see live demo). Is there any reason why this would be a bad idea?

I currently solve it with `z-index`, but I would prefer not having to override that. It creates an encapsulation leak since it seems my parent elements have to be aware of the `z-index` used.

Another solution is for `paper-item` to provide an extension point for secondary action elements.

### Expected outcome

The secondary actions element becomes shaded just like the rest of the item. (Red shade in the live demo.)

### Actual outcome

Everything except the secondary actions element gets a shade.

### Live Demo

https://jsbin.com/cawomiboqo/edit?html,css,output

### Steps to reproduce

Click to focus each item and look at the box to the right.

### Browsers Affected

At least Chrome. Probably all.

**Comment by bicknellr** [comment]
Hi @tommie, thanks for taking the time to file this but I think we'd prefer to keep using `:after` so that we can avoid tinting the content (text, items, etc.., not just the background) of the item. I think you should try rearranging your layout so that the actions aren't sitting above the regular content when they're visible so they wouldn't require a background to block what's below. Here's a demo that might be something like what you're looking for: https://jsbin.com/voqupa/1/edit?html,css,output.

**Comment by tommie** [comment]
> but I think we'd prefer to keep using `:after` so that we can avoid tinting the content (text, items, etc.., not just the background) of the item.

(I think you mean `:before` here.)

Ah, so *not* tinting the children is by design in `paper-item`, and it's really just supposed to be the background changing? I couldn't find anything in Material Design about focus tinting, and I just assumed it should tint everything.

**Comment by bicknellr** [comment]
Yup, meant `:before`, thanks! I haven't been able to find anything after a quick skim of the spec that indicates whether or not content is meant to be tinted, all the examples show text which is the same color as the ripple / highlight so there's no way to tell, but it seems like it would be odd to do that for anything other than text. Glad to hear the demo was helpful though!
