### ISSUE TITLE
Remove typography.html import

### ISSUE THREAD

**Issue by abdonrd** [PolymerElements/paper-item#92]
### Description

With the typography.html, loads Roboto font.
[PolymerElements/paper-item/paper-item-shared-styles.html#L14](https://github.com/PolymerElements/paper-item/blob/master/paper-item-shared-styles.html#L14)
### Expected outcome

Not load Roboto font, like other elements.
Example: https://github.com/PolymerElements/paper-toast/pull/58
### Actual outcome

Loads Roboto font.

**Comment by notwaldorf** [comment]
As mentioned in https://github.com/PolymerElements/paper-input/issues/412, this is a breaking change and we will deal with this for all the elements at once, in the 2.0 release.

**Comment by abdonrd** [comment]
As far as I know, the Polymer Elements are not going to continue developing. So I close this issue.
